### ISSUE TITLE
Two errors stopping me from compiling, when all I want is to remove the text it spams.

### ISSUE THREAD

**Issue by srehk** [AlbinoDrought/LoveBoot#23]
Severity    Code    Description Project File    Line    Suppression State
Error   CS1501  No overload for method 'Draw' takes 2 arguments LoveBoot    

Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'TemplateMatchingType' does not exist in the namespace 'Emgu.CV.CvEnum' (are you missing an assembly reference?) LoveBoot    

Any ideas on a fix? I'm lost.

It's annoying enough to have to re-reference emgu and nuget, so if anyone can send me a version without the text spam, please do. 
skype: xxjontronxx

**Comment by AlbinoDrought** [comment]
Hello,

I think this might be happening because Emgu has changed some classes in a newer release (see http://stackoverflow.com/a/33442465/3649573 ), but I am not sure.

A possible solution is to update the project to work with the given version of Emgu (requires effort).

An easier solution is to use the Emgu DLL files packaged with LoveBoot releases. These are available on https://github.com/AlbinoDrought/LoveBoot/releases

If this doesn't work, let me know.

**Comment by srehk** [comment]
I thought that using the DLL's would work from the release as well, but to no avail. 
I eventually gave up, as it is detected now anyway.

**Comment by sirioth** [comment]
I would like one without text spam too can anyone send it to me?
