### ISSUE TITLE
8 keys doesn't work in LoveRitmo 

### ISSUE THREAD

**Issue by prz31** [AlbinoDrought/LoveBoot#5]
Please friend could you solve this problem?  in LoveBeat Steam works very well but it doesn't work inLoveRitmo 8keys in any songs. Please :c

**Comment by fesnandu** [comment]
That's because the arrows in 7, 9, 1 and 3 have got different colors from the default ones

**Comment by AlbinoDrought** [comment]
Any chance you can take a picture of them and post it here?

You should be able to replace the corresponding files in the "Images/"
folder to make it work.

EX, for arrow pointing to the bottom left: Take a screenshot, crop out the
key, save as .png, name it "Key_8_Down_Left.png" and put it in the images
folder. The quality of your screenshot and crop will affect how well it is
detected - if you follow the format the images are already in, it should
work great.

**Comment by AlbinoDrought** [comment]
Actually, it detects them fine (You can see 8UR, 8UL, etc) and presses the key, it just does not register. I'll try to find out why.

**Comment by prz31** [comment]
friend, you might find some solution? I observe the colors of the arrows are the same as in the version of steam, please if you get solve the problem of 8 keys. Share it

**Comment by prz31** [comment]
friend what about the solution ? could you find it? please share it

**Comment by AlbinoDrought** [comment]
@prz31 Fixed in latest release: https://github.com/AlbinoDrought/LoveBoot/releases/tag/v0.01c

In LoveRitmo, it turns off numlock when you start an 8-key game. LoveBoot was still pressing the keys as if numlock was on, which works for the steam version but not LoveRitmo. 

It now checks if numlock is on, and if so presses the correct keys (Instead of numpad 7, it presses home, etc...)

Let me know how it goes!
