### ISSUE TITLE
Whyy

### ISSUE THREAD

**Issue by street141** [AlbinoDrought/LoveBoot#6]

**Comment by AlbinoDrought** [comment]
@street141 Sorry, the program is really intensive since it is doing a lot of image operations. Almost every frame, it is trying to:
- Take a screenshot of the keys and area below the keys
- Match every possible key (in 8-key mode, this is double the amount of work)
- Match bars so it knows when to press keys

These operations themselves are very expensive, and I'm sure my lack of experience with OpenCV does not help either.

The only things that could really help are:
- For the program to get optimized (lol)
- For you to upgrade your computer
- For you to use a less-intensive program to do the same thing, such as one that "cheats" and reads the memory of the program - I don't know if any of these exist.
